import { AdminLayout } from '@/components/layout';
import { useAuth } from '@/hooks/use-auth';
import { NextPageWithLayout } from '@/models/common';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { ReactElement } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  const { logout, profile } = useAuth();

  const handleLogoutClick = async () => {
    try {
      await logout();
      console.log('redirect to home');
    } catch (error) {
      console.log('Failed to logout', error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button onClick={handleLogoutClick}>Logout</button>

        <p>{JSON.stringify(profile)}</p>

        <Link href="/posts">
          <a>Go to post list page</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

Home.getLayout = function getLayout(page: ReactElement) {
  return <AdminLayout>{page}</AdminLayout>;
};
